V1 (02 11 2025): Translated from R to Python and added the visualizations for goals B to D


V2 (04 01 2025): Loop system implemented

V2.5 (04 02 2025): Loops system tweaks. Removed openpyxl as it was corrupting files and replaced it with xlwings

V3 & V4 finalize the loop except for the tax and asset channel

V 5,6,7 add tax shenanigans. V7C added the fully functioning inflow and outflow of wealth with the returns and taxes in it.

V8 modifies the aktiesparekonto pool so that it is increased when taxes are payed.

V9 substracts from the wealth pool the amount for the goals reached. It does not just substract the full amount of the goal, but rather the % from the allocation of the year prior to the goal being handed.

V10 Corrects returns to be inflation adjusted



In [111]:
#!pip install numpy pandas scipy matplotlib xlwings

In [112]:
import numpy as np
from scipy.stats import norm
import pandas as pd
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import os
import subprocess
import xlwings as xw
import time


In [113]:
# -- Variable Setup -- ##

#Monte Carlo Trials
n_trials = 10**5

# -V10 - Static Inflation
inflation_rate = 0.02  # 2%
#Case Study Profile Selection
Profile = "P1" #Either P1 or P2

#Excel worksheets
excel_returns = "Returns"
excel_volatilities = "Volatilities"
excel_correlation = "Correlation"
excel_gbi = "GBI Allocations P1" if Profile == "P1" else "GBI Allocations P2"
excel_gbi_goals = "GBI Goals P1" if Profile == "P1" else "GBI Goals P2"
excel_final_wealth = "FinalWealth"
excel_income = "Salary"


# Define Functions
This section defines the functions used for calculating portfolio volatility, expected return, 
goal achievement probability, and the objective (failure probability) to minimize.

In [114]:

def sd_f(weight_vector, covar_table):
    covar_vector = np.zeros(len(weight_vector))
    for z in range(len(weight_vector)):
        covar_vector[z] = np.sum(weight_vector * covar_table[:, z])
    return np.sqrt(np.sum(weight_vector * covar_vector))

In [115]:
def mean_f(weight_vector, return_vector):
    return np.sum(weight_vector * return_vector)

In [116]:
def phi_f(goal_vector, goal_allocation, pool, mean, sd):
    # goal_vector is [value ratio, funding requirement, time horizon]
    required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1
    if goal_allocation * pool >= goal_vector[1]:
        return 1
    else:
        return 1 - norm.cdf(required_return, loc=mean, scale=sd)

In [117]:
def optim_function(weights):
    # Uses the current global variables: goal_vector, allocation, pool, return_vector, covar_table
    return 1 - phi_f(
        goal_vector,
        allocation,
        pool,
        mean_f(weights, return_vector),
        sd_f(weights, covar_table)
    )

In [118]:
def constraint_function(weights):
    # For SciPy equality constraints, we require constraint_function(weights) == 0.
    return np.sum(weights) - 1

In [119]:
def mvu_f(weights):
    # mvu_f is defined for mean-variance optimization (not used below).
    return -(mean_f(weights, return_vector) - 0.5 * gamma * sd_f(weights, covariances)**2)

In [120]:
def r_req_f(goal_vector, goal_allocation, pool):
    return (goal_vector[1] / (goal_allocation * pool))**(1 / goal_vector[2]) - 1

In [121]:
# V 11 Utility Loss function for cashing out goal
def marginal_utility_loss_of_withdrawal(goal_amount, portfolio_value, future_goals, future_goal_weights, return_vector, covariances):
    loss = 0
    phi_list = []  # store tuples of (phi_without, phi_with)

    portfolio_after = portfolio_value - goal_amount
    for i, goal in enumerate(future_goals):
        alloc = future_goal_weights[i]
        mean = mean_f(alloc, return_vector)
        sd = sd_f(alloc, covariances)
        phi_with = phi_f(goal, 1, portfolio_after, mean, sd)
        phi_without = phi_f(goal, 1, portfolio_value, mean, sd)
        value_score = goal[0]
        loss += value_score * (phi_without - phi_with)

        phi_list.append((phi_without, phi_with))  # store values

    return loss, phi_list


In [122]:
def get_goal_data(master_excel_path, plan=Profile):
    """
    Returns a DataFrame of the specified goal table (P1 or P2).
    P1 => B2:F5
    P2 => B7:F10
    """
    if plan == "P1":
        skip = 1  # start reading at row 2
    elif plan == "P2":
        skip = 6  # start reading at row 7
    else:
        raise ValueError("Plan not recognized. Use 'P1' or 'P2'.")

    df_goals = pd.read_excel(master_excel_path,sheet_name="Goals",skiprows=skip,nrows=4,usecols="B:F",header=0)
    # First column is "Goal Info", so make that the index
    df_goals.set_index(df_goals.columns[0], inplace=True)
    return df_goals



# Load & Parse Data

In [123]:

## -- Repo Root and Folders -- ##

# Get repo root and set folders
root = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True).stdout.strip()
data_folder = os.path.join(root, "GBI Optimisation", "data")
output_folder = os.path.join(root, "GBI Optimisation")

# Get excel file and sheets
master_excel_path = os.path.join(data_folder, "Master.xlsx")

df_returns = pd.read_excel(master_excel_path, sheet_name=excel_returns)
df_vols = pd.read_excel(master_excel_path, sheet_name=excel_volatilities)

df_returns.set_index(df_returns.columns[0], inplace=True)
df_vols.set_index(df_vols.columns[0], inplace=True)

df_corr = pd.read_excel(master_excel_path, sheet_name=excel_correlation)
df_corr.set_index(df_corr.columns[0], inplace=True)


In [124]:
# - NEW V8 CONTENT REGARDING AKTIESPAREKONTO ALLOCATION - #

# Initial cap in 2025
initial_ask_cap = 166200
growth_rate = 0.1265  # 12.65% annual increase
aktiesparekonto_used_total = 0


In [125]:
asset_level_log = []  # NEW: Log each asset's return pre- and post-tax by account

while True:
    ## -- Loop Table -- ##
    table_loop_df = pd.read_excel(master_excel_path, sheet_name="Loop",usecols="B:F",skiprows=1,header=0)
    # Find Last looped year and select the next one
    # Filter only rows where LoopStatus is N
    pending_rows = table_loop_df[table_loop_df["LoopStatus"] == "N"]

    # If we find any rows, get the row with the lowest Year
    if pending_rows.empty:
        print("All loops completed")
        break


    chosen_row = pending_rows.loc[pending_rows["Year"].idxmin()]
    loop_year = chosen_row["Year"]
    loop_number = chosen_row["N"]
    loop_age1 = chosen_row["AgeP1"]
    loop_age2 = chosen_row["AgeP2"]

    print(loop_year, loop_number, loop_age1, loop_age2)

    # - Wealth - #

    # Get salary for current year
    df_salary = pd.read_excel(master_excel_path, sheet_name=excel_income)
    df_salary.set_index(df_salary.columns[0], inplace=True)
    salary = df_salary.loc[Profile, str(loop_year)]

    # Load FinalWealth sheet
    df_final_wealth = pd.read_excel(master_excel_path, sheet_name=excel_final_wealth)
    df_final_wealth.set_index(df_final_wealth.columns[0], inplace=True)

    # - Dynamic time horizon based on current year - #

    # Step 1: Get Starting Year (minimum year in Loop sheet)
    starting_year = table_loop_df["Year"].min()
    prev_year = str(loop_year - 1)

    # If first loop year, no previous wealth exists
    if loop_year == starting_year:
        prev_wealth = 0
        pool = salary
    else:
        try:
            prev_wealth = df_final_wealth.loc[Profile, prev_year]
        except KeyError:
            raise KeyError(f"Previous wealth not found for {Profile} in {prev_year}")
        pool = salary + prev_wealth

    capital_market_expectations_raw = {}
    for asset in df_returns.index:
        expected_return = df_returns.loc[asset, str(loop_year)]
        volatility = df_vols.loc[asset, 'volatility']
        capital_market_expectations_raw[asset] = {
            'Return Forecast': expected_return,
            'Volatility Forecast': volatility
        }

    capital_market_expectations_raw = pd.DataFrame.from_dict(capital_market_expectations_raw, orient='index')

    capital_market_expectations_raw = capital_market_expectations_raw.reset_index()
    capital_market_expectations_raw.rename(columns={'index': 'Unnamed: 0'}, inplace=True)

    # Rearrange columns to match your old format (optional):
    capital_market_expectations_raw = capital_market_expectations_raw[['Unnamed: 0', 'Return Forecast', 'Volatility Forecast']]

    goal_data_raw = get_goal_data(master_excel_path, plan="P1")

    # - Dynamic time horizon based on current year - #


    # Step 2: Compute Goal Years = starting_year + time_horizon
    goal_horizons = goal_data_raw.loc["Time Horizon"].astype(int)
    goal_years = starting_year + goal_horizons

    # Step 3: Recalculate Time Horizons = goal_years - current loop_year
    adjusted_horizons = goal_years - loop_year

    # Step 4: Replace the "Time Horizon" row in goal_data_raw
    goal_data_raw.loc["Time Horizon"] = adjusted_horizons

    # - V8 - Dynamically compute ASK cap per year
    aktiesparekonto_cap = initial_ask_cap * ((1 + growth_rate) ** (loop_year - starting_year))

    goals = ["A", "B", "C", "D"]
    active_goal_mask = np.array([adjusted_horizons[f"GOAL {g}"] > 0 for g in goals])

    # Optional: print to confirm
    print("Starting Year:", starting_year)
    print("Current Year:", loop_year)
    print("Goal Years:", goal_years.to_dict())
    print("Adjusted Horizons:", adjusted_horizons.to_dict())



    # Record number of potential investments and goals
    num_assets = capital_market_expectations_raw.shape[0]
    num_goals = goal_data_raw.shape[1]

    # Create vector of expected returns
    return_vector = (capital_market_expectations_raw["Return Forecast"] - inflation_rate).to_numpy()

    # Get the correlations as a numeric DataFrame (just a num_assets × num_assets block)
    correlations = df_corr.iloc[:num_assets, :num_assets].astype(float)

    # Build the covariance matrix: stdev_i * stdev_j * correlation_ij
    stdevs = capital_market_expectations_raw["Volatility Forecast"].to_numpy()
    covariances = np.zeros((num_assets, num_assets))
    for i in range(num_assets):
        for j in range(num_assets):
            covariances[i, j] = stdevs[i] * stdevs[j] * correlations.iloc[i, j]

    goal_A = goal_data_raw["GOAL A"].values
    goal_B = goal_data_raw["GOAL B"].values
    goal_C = goal_data_raw["GOAL C"].values
    goal_D = goal_data_raw["GOAL D"].values

    # - Optimal Goal Allocation - #


    goal_allocation = np.arange(0.01, 1.01, 0.01)

    # Starting weights (random initialization normalized to sum to 1)
    starting_weights = np.random.uniform(0, 1, num_assets)
    starting_weights /= np.sum(starting_weights)

    # Initialize matrices to store the optimal weights for each goal
    optimal_weights_A = np.zeros((len(goal_allocation), num_assets))
    optimal_weights_B = np.zeros((len(goal_allocation), num_assets))
    optimal_weights_C = np.zeros((len(goal_allocation), num_assets))
    optimal_weights_D = np.zeros((len(goal_allocation), num_assets))

    goal_allocation = np.arange(0.01, 1.01, 0.01)

    # Set SLSQP options to be more stringent, mimicking solnp's behavior.
    slsqp_opts = {
        'ftol': 1e-12,     # function tolerance
        'eps': 1e-12,      # finite-difference step size for gradient estimation
        'maxiter': 10000,  # maximum iterations
        'disp': False     # do not display convergence messages
    }

    for i, alloc in enumerate(goal_allocation):
        allocation = alloc      # Global variable used in optim_function
        covar_table = covariances

        # Goal A Optimization
        goal_vector = goal_A   # Global variable used in optim_function
        if goal_A[1] <= pool * allocation:
            optimal_weights_A[i, :] = [0]*(num_assets - 1) + [1]
        else:
            result = minimize(
                optim_function,
                starting_weights,
                constraints=[{'type': 'eq', 'fun': constraint_function}],
                bounds=[(0, 1)] * num_assets,
                method='SLSQP',
                options=slsqp_opts
            )
            optimal_weights_A[i, :] = result.x

        # Goal B Optimization
        goal_vector = goal_B
        if goal_B[1] <= pool * allocation:
            optimal_weights_B[i, :] = [0]*(num_assets - 1) + [1]
        else:
            result = minimize(
                optim_function,
                starting_weights,
                constraints=[{'type': 'eq', 'fun': constraint_function}],
                bounds=[(0, 1)] * num_assets,
                method='SLSQP',
                options=slsqp_opts
            )
            optimal_weights_B[i, :] = result.x

        # Goal C Optimization
        goal_vector = goal_C
        if goal_C[1] <= pool * allocation:
            optimal_weights_C[i, :] = [0]*(num_assets - 1) + [1]
        else:
            result = minimize(
                optim_function,
                starting_weights,
                constraints=[{'type': 'eq', 'fun': constraint_function}],
                bounds=[(0, 1)] * num_assets,
                method='SLSQP',
                options=slsqp_opts
            )
            optimal_weights_C[i, :] = result.x

        # Goal D Optimization
        goal_vector = goal_D
        if goal_D[1] <= pool * allocation:
            optimal_weights_D[i, :] = [0]*(num_assets - 1) + [1]
        else:
            result = minimize(
                optim_function,
                starting_weights,
                constraints=[{'type': 'eq', 'fun': constraint_function}],
                bounds=[(0, 1)] * num_assets,
                method='SLSQP',
                options=slsqp_opts
            )
            optimal_weights_D[i, :] = result.x

    # Calculate the best probability (phi) for each allocation level for every goal
    phi_A = np.zeros(len(goal_allocation))
    phi_B = np.zeros(len(goal_allocation))
    phi_C = np.zeros(len(goal_allocation))
    phi_D = np.zeros(len(goal_allocation))

    for i, alloc in enumerate(goal_allocation):
        phi_A[i] = phi_f(goal_A, alloc, pool,
                         mean_f(optimal_weights_A[i, :], return_vector),
                         sd_f(optimal_weights_A[i, :], covariances))
        phi_B[i] = phi_f(goal_B, alloc, pool,
                         mean_f(optimal_weights_B[i, :], return_vector),
                         sd_f(optimal_weights_B[i, :], covariances))
        phi_C[i] = phi_f(goal_C, alloc, pool,
                         mean_f(optimal_weights_C[i, :], return_vector),
                         sd_f(optimal_weights_C[i, :], covariances))
        phi_D[i] = phi_f(goal_D, alloc, pool,
                         mean_f(optimal_weights_D[i, :], return_vector),
                         sd_f(optimal_weights_D[i, :], covariances))

    # Simulate goal weights: each row is a simulated allocation (in percentages)
    sim_goal_weights = np.random.multinomial(100, [1/num_goals]*num_goals, size=n_trials) #this one sums to 100 so its good
    for i in range(n_trials):
        rand_vector = np.random.uniform(0, 1, num_goals)
        normalizer = np.sum(rand_vector)
        percents = np.round((rand_vector / normalizer) * 100, 0)

        # Only enforce floor for active goals
        floor_applied = np.where(active_goal_mask, np.maximum(percents, 1), percents)
        sim_goal_weights[i, :] = floor_applied


    # Calculate utility for each simulated portfolio.
    # Note: subtract 1 from simulated weights for 0-indexing.
    utility = (
        goal_A[0] * phi_A[sim_goal_weights[:, 0] - 1] +
        goal_A[0] * goal_B[0] * phi_B[sim_goal_weights[:, 1] - 1] +
        goal_A[0] * goal_B[0] * goal_C[0] * phi_C[sim_goal_weights[:, 2] - 1] +
        goal_A[0] * goal_B[0] * goal_C[0] * goal_D[0] * phi_D[sim_goal_weights[:, 3] - 1]
    )

    # Find the index of the portfolio with the highest utility
    index = np.argmax(utility)
    optimal_goal_weights = sim_goal_weights[index, :]

    # - Optimal Subportfolio Allocation - #

    # Retrieve optimal subportfolio allocations
    optimal_subportfolios = np.zeros((num_goals, num_assets))

    # For each goal, use the simulated percentage to select the corresponding row
    # from the optimal weights matrix (adjust for zero-indexing)
    for i in range(num_goals):
        optimal_subportfolios[i, :] = eval(f"optimal_weights_{goals[i]}")[optimal_goal_weights[i] - 1, :]

    # Compute the optimal aggregate investment portfolio.
    optimal_aggregate_portfolio = (optimal_goal_weights / 100) @ optimal_subportfolios

    #Define asset names
    asset_names = capital_market_expectations_raw.iloc[:, 0].astype(str).tolist()

    # - Storing and exporting results - #

    # Create a DataFrame for the aggregate portfolio.
    # First calculate unrounded percentages
    raw_alloc = optimal_aggregate_portfolio * 100

    # Normalize to force sum = 100 after rounding
    normalized_alloc = raw_alloc / raw_alloc.sum() * 100
    normalized_goal_alloc = np.zeros_like(optimal_goal_weights, dtype=float)
    active_sum = np.sum(optimal_goal_weights[active_goal_mask])
    normalized_goal_alloc[active_goal_mask] = (optimal_goal_weights[active_goal_mask] / active_sum) * 100

    normalized_weights = normalized_alloc / 100  # convert back to decimal weights

    # Create a DataFrame for the across-goal allocation.
    df_across_goal = pd.DataFrame({
        "Goal": goals,
        "Allocation (%)": np.round(normalized_goal_alloc, 2) # Keep raw percentages
    })

    # Round after normalization
    df_aggregate = pd.DataFrame({
        "Asset": asset_names,
        "Weight": normalized_weights,
        "Invested Amt (DKK)": normalized_weights * pool,
        "Allocation (%)": np.round(normalized_alloc, 2)  # keep for display only
    })


    # - NEW V5 CONTENT REGARDING AKTIESPAREKONTO ALLOCATION - #
    # --- NEW: Exact and Proportional ASK Logic ---
    account_allocations = []
    equity_rows = []
    non_equity_rows = []

    # First pass: split equity and non-equity rows
    for i, row in df_aggregate.iterrows():
        asset_name = row["Asset"]
        invested = row["Invested Amt (DKK)"]
        weight = row["Weight"]

        row_dict = {
            "Year": loop_year,
            "Asset": asset_name,
            "Invested": invested,
            "Weight": weight,
            "ASK (DKK)": 0,
            "Normal (DKK)": 0,
        }

        if "Equities" in asset_name:
            equity_rows.append(row_dict)
        else:
            row_dict["Normal (DKK)"] = invested
            non_equity_rows.append(row_dict)

    # Determine total equity to allocate proportionally if ASK cap remains
    total_equity = sum(row["Invested"] for row in equity_rows)
    remaining_ask_cap = max(0, aktiesparekonto_cap - aktiesparekonto_used_total)
    ask_fraction = min(1, remaining_ask_cap / total_equity) if total_equity > 0 else 0

    # Apply proportional ASK allocation to equities
    for row in equity_rows:
        ask_part = row["Invested"] * ask_fraction
        normal_part = row["Invested"] - ask_part
        row["ASK (DKK)"] = round(ask_part, 2)
        row["Normal (DKK)"] = round(normal_part, 2)
        aktiesparekonto_used_total += ask_part

    # Combine and finalize
    account_allocations = equity_rows + non_equity_rows


    df_accounts = pd.DataFrame(account_allocations)
    print(f"[DEBUG] Final weight sum: {sum(row['Weight'] for row in account_allocations):.10f}")
    # - V5 END - #


    # - NEW V6 CONTENT REGARDING GAINS & TAXES - #


    share_income_normal = 0  # for progressive tax
    tax_ask = 0  # Track ASK tax separately

    # Update portfolio and compute gains
    for row in account_allocations:
        asset = row["Asset"]
        ask = row["ASK (DKK)"]
        normal = row["Normal (DKK)"]
        weight = row["Weight"]
        expected_return_nominal = capital_market_expectations_raw.loc[
            capital_market_expectations_raw["Unnamed: 0"] == asset,
            "Return Forecast"
        ].values[0]
        expected_return_inflation_adj = (
            capital_market_expectations_raw.loc[
                capital_market_expectations_raw["Unnamed: 0"] == asset,
                "Return Forecast"
            ].values[0] - inflation_rate
        )

        # V7C -LOG ASSET RETURNS BY ACCOUNT
        if ask > 0:
            new_val = ask * (1 + expected_return_inflation_adj)
            gain = new_val - ask
            tax = 0.17 * gain
            asset_level_log.append({
                "Year": loop_year,
                "Account": "ASK",
                "Asset": asset,
                "Invested": ask,
                "Weight": ask / pool,
                "Return (Nominal)": expected_return_nominal,
                "Inflation Rate": inflation_rate,
                "Return (Inflation Adjusted)": expected_return_inflation_adj,
                "Gross Gain": gain,
                "Tax": tax,
                "Net Gain": gain - tax,
                "End Value": ask + gain - tax,
                "TOTAL ASK Cap (DKK)": aktiesparekonto_cap
            })

        if normal > 0:
            new_val = normal * (1 + expected_return_inflation_adj)
            gain = new_val - normal
            share_income_normal += gain
            asset_level_log.append({
                "Year": loop_year,
                "Account": "NORMAL",
                "Asset": asset,
                "Invested": normal,
                "Weight": normal / pool,
                "Return (Nominal)": expected_return_nominal,
                "Inflation Rate": inflation_rate,
                "Return (Inflation Adjusted)": expected_return_inflation_adj,
                "Gross Gain": gain,
                "Tax": None,  # progressive tax logged later
                "Net Gain": None,
                "End Value": None,
                "TOTAL ASK Cap (DKK)": aktiesparekonto_cap
            })

            #V7C END

    # Tax on Normal Account (progressive)
    cap = 67500
    if share_income_normal <= cap:
        tax_normal = 0.27 * share_income_normal
    else:
        tax_normal = 0.27 * cap + 0.42 * (share_income_normal - cap)

    # Distribute tax proportionally across NORMAL assets
    normal_log_rows = [
        row for row in asset_level_log
        if row["Account"] == "NORMAL" and row["Year"] == loop_year
    ]
    total_normal_gain = sum(row["Gross Gain"] for row in normal_log_rows)

    print(f"[DEBUG] Year: {loop_year}")
    print(f"[DEBUG] Gross Gains (Normal account): {share_income_normal:.2f}")
    print(f"[DEBUG] Tax Calculated (Normal account): {tax_normal:.2f}")

    for row in normal_log_rows:
        if total_normal_gain > 0:
            share = row["Gross Gain"] / total_normal_gain
            tax = share * tax_normal
        else:
            tax = 0

        row["Tax"] = tax
        row["Net Gain"] = row["Gross Gain"] - tax
        row["End Value"] = row["Invested"] + row["Net Gain"]

    total_gains_normal = share_income_normal - tax_normal


    print("Optimal Across-Goal Allocation:")
    print(df_across_goal.to_string(index=False))

    print("\nOptimal Aggregate Investment Allocation:")
    print(df_aggregate.to_string(index=False))

    print("\nUtility:")
    print(utility)

    print("\nProbability of Achieving Each Goal at Optimal Allocation:")
    print(f"Goal A: {phi_A[optimal_goal_weights[0] - 1]:.4f}")
    print(f"Goal B: {phi_B[optimal_goal_weights[1] - 1]:.4f}")
    print(f"Goal C: {phi_C[optimal_goal_weights[2] - 1]:.4f}")
    print(f"Goal D: {phi_D[optimal_goal_weights[3] - 1]:.4f}")

    # -- Safer Excel launch --
    app = xw.App(visible=False)
    app.display_alerts = False
    app.screen_updating = False

    time.sleep(1)

    # Open workbook
    wb = app.books.open(master_excel_path)
    ws = wb.sheets[excel_gbi]
    ws_final_wealth = wb.sheets[excel_final_wealth]

    # Get header values from row 1 (columns B to AY ~= cols 2 to 51)
    header_values = [ws.cells(1, col).value for col in range(2, 53)]

    try:
        year_col = header_values.index(str(loop_year)) + 2
    except ValueError:
        raise ValueError(f"Year {loop_year} not found in worksheet headers.")

    # Write weights
    for i, asset in enumerate(asset_names):
        allocation = float(np.round(normalized_alloc[i], 2)) / 100
        cell = ws.cells(i + 2, year_col)
        cell.value = allocation
        cell.number_format = '0.00%'  # display as percentage

    # -- Export Goal Weights to Excel -- #

    # Re-access the sheet after workbook is open
    ws_goals = wb.sheets[excel_gbi_goals]

    # Read header values from row 1 (columns B to AY ≈ cols 2 to 52)
    goal_header_values = [ws_goals.cells(1, col).value for col in range(2, 53)]

    try:
        goal_year_col = goal_header_values.index(str(loop_year)) + 2
    except ValueError:
        raise ValueError(f"Year {loop_year} not found in goal worksheet headers.")

    # Write each across-goal allocation to the appropriate row
    for i, allocation in enumerate(df_across_goal["Allocation (%)"]):
        value = float(np.round(allocation / 100, 6))  # convert to decimal
        row = i + 2  # assuming goal names are in rows starting at 2
        cell = ws_goals.cells(row, goal_year_col)
        cell.value = value
        cell.number_format = '0.00%'  # display as percentage

    # -- Modify Loop Check -- #
    print("Starting loop status check...")

    ws_loop = wb.sheets["Loop"]
    print("Accessed 'Loop' worksheet.")

    # Read data range again (columns B to F)
    last_row = ws_loop.cells.last_cell.row
    print(f"Last cell row: {last_row}")

    loop_data = ws_loop.range("B2:F" + str(last_row)).value
    print(f"Loaded loop data. Total rows read: {len(loop_data)}")

    # Find and update the matching year with LoopStatus 'N'
    found = False
    for i, row in enumerate(loop_data):
        year = row[1]
        status = row[4]
        print(f"Row {i+2}: Year = {year}, Status = {status}")
        if year == loop_year and status == 'N':
            print(f"Match found at row {i+2}. Updating status to 'Y'.")
            ws_loop.cells(i + 2, 6).value = 'Y'  # Column F is column 6
            found = True
            break

    if not found:
        print(f"No matching row found for year {loop_year} with status 'N'.")
    else:
        print("Status updated successfully.")

    # Update FinalWealth sheet with new pool
    final_header_values = [ws_final_wealth.cells(1, col).value for col in range(2, 53)]
    try:
        final_year_col = final_header_values.index(str(loop_year)) + 2
    except ValueError:
        raise ValueError(f"Year {loop_year} not found in FinalWealth headers.")

    profile_row = 2 if Profile == "P1" else 3
    # Calculate total value of all assets across both accounts

    this_year_rows = [row for row in asset_level_log if row["Year"] == loop_year]
    end_value_sum = sum(row["End Value"] for row in this_year_rows)

    # - V9 - If a goal has 1 year left, annotate allocation & amount taken in asset_level_log --- #
    goal_payout_info = {}

    for i, goal in enumerate(goals):
        if adjusted_horizons[f"GOAL {goal}"] == 1:
            alloc_pct = normalized_goal_alloc[i]
            goal_required = goal_data_raw.loc["Funding Requirement", f"GOAL {goal}"]
            amount_alloc_based = (alloc_pct / 100) * end_value_sum

            # Set up future goals and weights (excluding the current goal)
            future_goals = [
                goal_data_raw[f"GOAL {g}"].values
                for j, g in enumerate(goals)
                if g != goal and adjusted_horizons[f"GOAL {g}"] > 1
            ]
            future_weights = [
                optimal_subportfolios[j, :]
                for j, g in enumerate(goals)
                if g != goal and adjusted_horizons[f"GOAL {g}"] > 1
            ]

            # Calculate marginal loss from funding the goal
            utility_loss, utility_details = marginal_utility_loss_of_withdrawal(
                goal_required,
                end_value_sum,
                future_goals,
                future_weights,
                return_vector,
                covariances
            )
            value_now = goal_data_raw.loc["Value Ratio", f"GOAL {goal}"]

            if value_now >= utility_loss:
                amount_taken = min(goal_required, amount_alloc_based)
                print(f"[DECISION] Paying Goal {goal} | Value: {value_now:.3f}, Loss to future: {utility_loss:.3f}")
                goal_payout_info[f"Goal {goal} Allocation (%)"] = alloc_pct
                goal_payout_info[f"Goal {goal} Amount Taken (DKK)"] = amount_taken
                end_value_sum -= amount_taken
                goal_payout_info[f"Goal {goal} Utility Loss"] = utility_loss
                goal_payout_info[f"Goal {goal} Value Now"] = value_now
                goal_payout_info[f"Goal {goal} Utility φ_before"] = ", ".join(str(round(p[0], 4)) for p in utility_details)
                goal_payout_info[f"Goal {goal} Utility φ_after"] = ", ".join(str(round(p[1], 4)) for p in utility_details)

            else:
                print(f"[DECISION] Skipping Goal {goal} | Value: {value_now:.3f}, Loss to future: {utility_loss:.3f}")
                goal_payout_info[f"Goal {goal} Allocation (%)"] = alloc_pct
                goal_payout_info[f"Goal {goal} Amount Taken (DKK)"] = 0
                goal_payout_info[f"Goal {goal} Utility Loss"] = utility_loss
                goal_payout_info[f"Goal {goal} Value Now"] = value_now
                goal_payout_info[f"Goal {goal} Utility φ_before"] = ", ".join(str(round(p[0], 4)) for p in utility_details)
                goal_payout_info[f"Goal {goal} Utility φ_after"] = ", ".join(str(round(p[1], 4)) for p in utility_details)


    # Annotate each row in asset_level_log for current year
    for row in asset_level_log:
        if row["Year"] == loop_year:
            for key, value in goal_payout_info.items():
                row[key] = value
    # - V9 END -

    ws_final_wealth.cells(profile_row, final_year_col).value = end_value_sum

    print(f"\n--- Year {loop_year} Summary ---")
    print(f"Income (Salary): {salary:.2f}")
    if loop_year != starting_year:
        print(f"Previous Wealth Carried: {prev_wealth:.2f}")
    print(f"Post-Tax Wealth (New Final Wealth): {pool:.2f}")
    print("------------------------------\n")

    wb.save()
    wb.close()
    app.quit()
    time.sleep(1)
    table_loop_df = pd.read_excel(master_excel_path, sheet_name="Loop", usecols="B:F", skiprows=1, header=0)


2025 1 25 40
Starting Year: 2025
Current Year: 2025
Goal Years: {'GOAL A': 2050, 'GOAL B': 2075, 'GOAL C': 2025, 'GOAL D': 2025}
Adjusted Horizons: {'GOAL A': 25, 'GOAL B': 50, 'GOAL C': 0, 'GOAL D': 0}


C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1
C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: invalid value encountered in scalar divide
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2025
[DEBUG] Gross Gains (Normal account): 0.00
[DEBUG] Tax Calculated (Normal account): 0.00
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           27.08
   B           72.92
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.045195                 0.0            4.52
        Developed Markets - Equities 0.201919                 0.0           20.19
Emerging Markets State - Obligations 0.135782                 0.0           13.58
      High Yield Bonds - Obligations 0.018742                 0.0            1.87
Investment Grade Bonds - Obligations 0.078000                 0.0            7.80
   Government ZC Bonds - Obligations 0.520363                 0.0           52.04

Utility:
[0. 0. 0. ... 0. 0. 0.]

Probability of Achieving Each Goal at Optimal Allocation:
Goal A:

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2026
[DEBUG] Gross Gains (Normal account): 8.74
[DEBUG] Tax Calculated (Normal account): 2.36
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           86.73
   B           13.27
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.800000e-01        5.159230e+04            98.0
        Developed Markets - Equities 3.950445e-15        2.079720e-10             0.0
Emerging Markets State - Obligations 4.346331e-15        2.288135e-10             0.0
      High Yield Bonds - Obligations 1.182105e-15        6.223214e-11             0.0
Investment Grade Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
   Government ZC Bonds - Obligations 2.000000e-02        1.052904e+03             2.0

Utility:
[0.0809072  0.05091208 0.06934951 ... 0.11252223 0.05091208 0.

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2027
[DEBUG] Gross Gains (Normal account): 9.10
[DEBUG] Tax Calculated (Normal account): 2.46
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           87.76
   B           12.24
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.898990e-01        1.074672e+05           98.99
        Developed Markets - Equities 3.681359e-18        3.996624e-13            0.00
Emerging Markets State - Obligations 2.061403e-16        2.237938e-11            0.00
      High Yield Bonds - Obligations 4.051518e-17        4.398482e-12            0.00
Investment Grade Bonds - Obligations 2.927762e-17        3.178490e-12            0.00
   Government ZC Bonds - Obligations 1.010101e-02        1.096604e+03            1.01

Utility:
[0.10777396 0.1136535  0.15442799 ... 0.1001666  0.07319691 0.

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2028
[DEBUG] Gross Gains (Normal account): 5872.29
[DEBUG] Tax Calculated (Normal account): 1585.52
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           86.73
   B           13.27
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.800000e-01        1.698337e+05            98.0
        Developed Markets - Equities 2.866045e-16        4.966846e-11             0.0
Emerging Markets State - Obligations 2.539689e-16        4.401273e-11             0.0
      High Yield Bonds - Obligations 1.991219e-15        3.450776e-10             0.0
Investment Grade Bonds - Obligations 2.906937e-16        5.037711e-11             0.0
   Government ZC Bonds - Obligations 2.000000e-02        3.465993e+03             2.0

Utility:
[0.15799311 0.18403492 0.25697663 ... 0.20035759 0.19756

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2029
[DEBUG] Gross Gains (Normal account): 13389.64
[DEBUG] Tax Calculated (Normal account): 3615.20
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           83.84
   B           16.16
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.900000e-01        2.389549e+05            99.0
        Developed Markets - Equities 0.000000e+00        0.000000e+00             0.0
Emerging Markets State - Obligations 1.056136e-13        2.549181e-08             0.0
      High Yield Bonds - Obligations 3.374314e-14        8.144534e-09             0.0
Investment Grade Bonds - Obligations 5.381508e-14        1.298927e-08             0.0
   Government ZC Bonds - Obligations 1.000000e-02        2.413686e+03             1.0

Utility:
[0.16057861 0.25073747 0.0979644  ... 0.06849986 0.0728

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2030
[DEBUG] Gross Gains (Normal account): 17338.80
[DEBUG] Tax Calculated (Normal account): 4681.48
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           83.51
   B           16.49
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.700000e-01        3.035580e+05            97.0
        Developed Markets - Equities 1.348921e-15        4.221400e-10             0.0
Emerging Markets State - Obligations 0.000000e+00        0.000000e+00             0.0
      High Yield Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
Investment Grade Bonds - Obligations 3.523323e-16        1.102611e-10             0.0
   Government ZC Bonds - Obligations 3.000000e-02        9.388392e+03             3.0

Utility:
[0.24694308 0.25907627 0.18868817 ... 0.12391644 0.0212

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2031
[DEBUG] Gross Gains (Normal account): 21762.29
[DEBUG] Tax Calculated (Normal account): 5875.82
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           91.84
   B            8.16
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.702970e-01        3.766801e+05           97.03
        Developed Markets - Equities 6.925154e-16        2.688422e-10            0.00
Emerging Markets State - Obligations 0.000000e+00        0.000000e+00            0.00
      High Yield Bonds - Obligations 0.000000e+00        0.000000e+00            0.00
Investment Grade Bonds - Obligations 0.000000e+00        0.000000e+00            0.00
   Government ZC Bonds - Obligations 2.970297e-02        1.153102e+04            2.97

Utility:
[0.1522866  0.16639282 0.22804643 ... 0.08605146 0.1935

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2032
[DEBUG] Gross Gains (Normal account): 27562.05
[DEBUG] Tax Calculated (Normal account): 7441.75
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A            89.9
   B            10.1
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 1.000000e+00        4.736215e+05           100.0
        Developed Markets - Equities 0.000000e+00        0.000000e+00             0.0
Emerging Markets State - Obligations 3.552185e-16        1.682391e-10             0.0
      High Yield Bonds - Obligations 7.307457e-17        3.460969e-11             0.0
Investment Grade Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
   Government ZC Bonds - Obligations 0.000000e+00        0.000000e+00             0.0

Utility:
[0.18599845 0.1336414  0.1301659  ... 0.30428421 0.2435

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2033
[DEBUG] Gross Gains (Normal account): 32382.53
[DEBUG] Tax Calculated (Normal account): 8743.28
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           91.84
   B            8.16
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.800000e-01        5.529130e+05            98.0
        Developed Markets - Equities 3.109914e-15        1.754604e-09             0.0
Emerging Markets State - Obligations 1.021855e-16        5.765272e-11             0.0
      High Yield Bonds - Obligations 7.963804e-18        4.493153e-12             0.0
Investment Grade Bonds - Obligations 2.097535e-17        1.183423e-11             0.0
   Government ZC Bonds - Obligations 2.000000e-02        1.128394e+04             2.0

Utility:
[0.25779858 0.16008546 0.18641215 ... 0.10952038 0.0894

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2034
[DEBUG] Gross Gains (Normal account): 37968.93
[DEBUG] Tax Calculated (Normal account): 10251.61
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A            89.8
   B            10.2
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.800000e-01        6.460765e+05            98.0
        Developed Markets - Equities 6.838974e-16        4.508674e-10             0.0
Emerging Markets State - Obligations 2.058800e-15        1.357288e-09             0.0
      High Yield Bonds - Obligations 1.400328e-15        9.231830e-10             0.0
Investment Grade Bonds - Obligations 3.670687e-15        2.419944e-09             0.0
   Government ZC Bonds - Obligations 2.000000e-02        1.318523e+04             2.0

Utility:
[0.31411792 0.24278903 0.22410528 ... 0.2478517  0.185

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2035
[DEBUG] Gross Gains (Normal account): 30013.98
[DEBUG] Tax Calculated (Normal account): 8103.77
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A            89.0
   B            11.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 1.000000e+00        7.594184e+05           100.0
        Developed Markets - Equities 0.000000e+00        0.000000e+00             0.0
Emerging Markets State - Obligations 1.976197e-16        1.500760e-10             0.0
      High Yield Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
Investment Grade Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
   Government ZC Bonds - Obligations 9.880985e-17        7.503802e-11             0.0

Utility:
[0.18319427 0.09596623 0.1355573  ... 0.25632505 0.3102

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2036
[DEBUG] Gross Gains (Normal account): 33541.53
[DEBUG] Tax Calculated (Normal account): 9056.21
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           86.73
   B           13.27
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.800000e-01        8.434993e+05            98.0
        Developed Markets - Equities 1.775368e-14        1.528084e-08             0.0
Emerging Markets State - Obligations 5.914876e-16        5.091014e-10             0.0
      High Yield Bonds - Obligations 1.211469e-16        1.042728e-10             0.0
Investment Grade Bonds - Obligations 2.434926e-17        2.095774e-11             0.0
   Government ZC Bonds - Obligations 2.000000e-02        1.721427e+04             2.0

Utility:
[0.09415665 0.09502931 0.09141692 ... 0.16547591 0.1893

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2037
[DEBUG] Gross Gains (Normal account): 37616.49
[DEBUG] Tax Calculated (Normal account): 10156.45
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A            94.9
   B             5.1
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.800000e-01        9.463204e+05            98.0
        Developed Markets - Equities 2.481383e-13        2.396105e-07             0.0
Emerging Markets State - Obligations 2.966942e-16        2.864977e-10             0.0
      High Yield Bonds - Obligations 4.312204e-16        4.164006e-10             0.0
Investment Grade Bonds - Obligations 5.521336e-16        5.331584e-10             0.0
   Government ZC Bonds - Obligations 2.000000e-02        1.931266e+04             2.0

Utility:
[0.08138389 0.05984997 0.10126803 ... 0.07590197 0.272

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2038
[DEBUG] Gross Gains (Normal account): 42124.80
[DEBUG] Tax Calculated (Normal account): 11373.70
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           91.92
   B            8.08
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.900000e-01        1.063873e+06            99.0
        Developed Markets - Equities 8.082424e-16        8.685528e-10             0.0
Emerging Markets State - Obligations 0.000000e+00        0.000000e+00             0.0
      High Yield Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
Investment Grade Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
   Government ZC Bonds - Obligations 1.000000e-02        1.074619e+04             1.0

Utility:
[0.05823242 0.181992   0.1077413  ... 0.08058574 0.161

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2039
[DEBUG] Gross Gains (Normal account): 46491.57
[DEBUG] Tax Calculated (Normal account): 12552.73
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           90.91
   B            9.09
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.900000e-01        1.176156e+06            99.0
        Developed Markets - Equities 6.629369e-15        7.875928e-09             0.0
Emerging Markets State - Obligations 1.085070e-16        1.289102e-10             0.0
      High Yield Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
Investment Grade Bonds - Obligations 9.992007e-17        1.187086e-10             0.0
   Government ZC Bonds - Obligations 1.000000e-02        1.188036e+04             1.0

Utility:
[0.09805124 0.04252009 0.2656468  ... 0.08739139 0.130

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2040
[DEBUG] Gross Gains (Normal account): 51324.70
[DEBUG] Tax Calculated (Normal account): 13857.67
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           91.92
   B            8.08
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.900000e-01        1.300647e+06            99.0
        Developed Markets - Equities 1.498908e-14        1.969243e-08             0.0
Emerging Markets State - Obligations 1.829518e-17        2.403593e-11             0.0
      High Yield Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
Investment Grade Bonds - Obligations 7.001164e-17        9.198025e-11             0.0
   Government ZC Bonds - Obligations 1.000000e-02        1.313785e+04             1.0

Utility:
[0.09691992 0.08914925 0.10673164 ... 0.29130048 0.093

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2041
[DEBUG] Gross Gains (Normal account): 56711.78
[DEBUG] Tax Calculated (Normal account): 15312.18
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           95.96
   B            4.04
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 2.953889e-01        4.266573e+05           29.54
        Developed Markets - Equities 7.046111e-01        1.017735e+06           70.46
Emerging Markets State - Obligations 1.435942e-16        2.074062e-10            0.00
      High Yield Bonds - Obligations 2.692675e-17        3.889278e-11            0.00
Investment Grade Bonds - Obligations 2.302218e-14        3.325305e-08            0.00
   Government ZC Bonds - Obligations 2.132771e-16        3.080557e-10            0.00

Utility:
[0.06811811 0.0805665  0.09675214 ... 0.08662579 0.068

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2042
[DEBUG] Gross Gains (Normal account): 59744.24
[DEBUG] Tax Calculated (Normal account): 16130.95
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           98.96
   B            1.04
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.241440        3.815540e+05           24.14
        Developed Markets - Equities 0.711598        1.124557e+06           71.16
Emerging Markets State - Obligations 0.001158        1.830721e+03            0.12
      High Yield Bonds - Obligations 0.001800        2.844416e+03            0.18
Investment Grade Bonds - Obligations 0.003721        5.881021e+03            0.37
   Government ZC Bonds - Obligations 0.040282        6.365902e+04            4.03

Utility:
[0.05637154 0.07301407 0.0379355  ... 0.0983817  0.20409761 0.0697597 ]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2043
[DEBUG] Gross Gains (Normal account): 66614.94
[DEBUG] Tax Calculated (Normal account): 17986.03
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           97.98
   B            2.02
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 2.663164e-01        4.580486e+05           26.63
        Developed Markets - Equities 7.236836e-01        1.244693e+06           72.37
Emerging Markets State - Obligations 2.596087e-17        4.465117e-11            0.00
      High Yield Bonds - Obligations 6.490038e-17        1.116248e-10            0.00
Investment Grade Bonds - Obligations 3.006324e-19        5.170700e-13            0.00
   Government ZC Bonds - Obligations 1.000000e-02        1.719941e+04            1.00

Utility:
[0.09712926 0.1159988  0.08260316 ... 0.1243031  0.200

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2044
[DEBUG] Gross Gains (Normal account): 72918.96
[DEBUG] Tax Calculated (Normal account): 20500.96
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A            97.0
   B             3.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 2.763057e-01        5.181326e+05           27.63
        Developed Markets - Equities 7.236943e-01        1.357082e+06           72.37
Emerging Markets State - Obligations 6.462874e-17        1.211928e-10            0.00
      High Yield Bonds - Obligations 1.100281e-17        2.063264e-11            0.00
Investment Grade Bonds - Obligations 2.608097e-17        4.890743e-11            0.00
   Government ZC Bonds - Obligations 7.217387e-18        1.353415e-11            0.00

Utility:
[0.03367354 0.09248198 0.05366332 ... 0.08698853 0.077

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2045
[DEBUG] Gross Gains (Normal account): 49248.22
[DEBUG] Tax Calculated (Normal account): 13297.02
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           96.97
   B            3.03
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 2.072760e-01        4.220154e+05           20.73
        Developed Markets - Equities 2.860136e-01        5.823256e+05           28.60
Emerging Markets State - Obligations 5.245882e-17        1.068065e-10            0.00
      High Yield Bonds - Obligations 0.000000e+00        0.000000e+00            0.00
Investment Grade Bonds - Obligations 0.000000e+00        0.000000e+00            0.00
   Government ZC Bonds - Obligations 5.067104e-01        1.031666e+06           50.67

Utility:
[0.09636501 0.08826995 0.02798669 ... 0.05254776 0.184

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2046
[DEBUG] Gross Gains (Normal account): 30268.76
[DEBUG] Tax Calculated (Normal account): 8172.57
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           96.88
   B            3.12
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 3.000000e-02        6.546484e+04             3.0
        Developed Markets - Equities 5.112577e-16        1.115647e-09             0.0
Emerging Markets State - Obligations 0.000000e+00        0.000000e+00             0.0
      High Yield Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
Investment Grade Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
   Government ZC Bonds - Obligations 9.700000e-01        2.116697e+06            97.0

Utility:
[0.14833081 0.0305261  0.30459477 ... 0.0721118  0.1153

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2047
[DEBUG] Gross Gains (Normal account): 30728.85
[DEBUG] Tax Calculated (Normal account): 8296.79
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           92.55
   B            7.45
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 7.000000e-02        1.617430e+05             7.0
        Developed Markets - Equities 3.414240e-17        7.888990e-11             0.0
Emerging Markets State - Obligations 7.873164e-18        1.819184e-11             0.0
      High Yield Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
Investment Grade Bonds - Obligations 2.156877e-18        4.983710e-12             0.0
   Government ZC Bonds - Obligations 9.300000e-01        2.148871e+06            93.0

Utility:
[0.10110204 0.0947837  0.09566426 ... 0.07965372 0.0973

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2048
[DEBUG] Gross Gains (Normal account): 29480.82
[DEBUG] Tax Calculated (Normal account): 7959.82
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           83.67
   B           16.33
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 1.600000e-01        3.926849e+05            16.0
        Developed Markets - Equities 0.000000e+00        0.000000e+00             0.0
Emerging Markets State - Obligations 9.228612e-17        2.264960e-10             0.0
      High Yield Bonds - Obligations 1.050712e-16        2.578742e-10             0.0
Investment Grade Bonds - Obligations 1.630015e-17        4.000514e-11             0.0
   Government ZC Bonds - Obligations 8.400000e-01        2.061595e+06            84.0

Utility:
[0.08326908 0.04371281 0.059786   ... 0.08948164 0.0522

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2049
[DEBUG] Gross Gains (Normal account): 31647.82
[DEBUG] Tax Calculated (Normal account): 8544.91
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A           79.38
   B           20.62
   C            0.00
   D            0.00

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 2.000000e-01        5.212866e+05            20.0
        Developed Markets - Equities 0.000000e+00        0.000000e+00             0.0
Emerging Markets State - Obligations 1.687886e-15        4.399361e-09             0.0
      High Yield Bonds - Obligations 1.515454e-15        3.949930e-09             0.0
Investment Grade Bonds - Obligations 1.154632e-15        3.009471e-09             0.0
   Government ZC Bonds - Obligations 8.000000e-01        2.085146e+06            80.0

Utility:
[6.88477809e-02 7.65708616e-02 3.34727656e-09 ... 8.823

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1
C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2050
[DEBUG] Gross Gains (Normal account): 15863.43
[DEBUG] Tax Calculated (Normal account): 4283.13
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.941775       719896.404093           94.18
        Developed Markets - Equities 0.001735         1325.874607            0.17
Emerging Markets State - Obligations 0.002436         1861.734179            0.24
      High Yield Bonds - Obligations 0.001598         1221.597127            0.16
Investment Grade Bonds - Obligations 0.001697         1296.974788            0.17
   Government ZC Bonds - Obligations 0.050760        38801.398762            5.08

Utility:
[0.03843534 0.03582747 0.01810138 ... 0.01136934 0.02443306 0.03757588]

Probabilit

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2051
[DEBUG] Gross Gains (Normal account): 20361.37
[DEBUG] Tax Calculated (Normal account): 5497.57
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.962404       873892.883205           96.24
        Developed Markets - Equities 0.002183         1982.510765            0.22
Emerging Markets State - Obligations 0.003030         2751.537100            0.30
      High Yield Bonds - Obligations 0.000388          352.165182            0.04
Investment Grade Bonds - Obligations 0.000416          377.315441            0.04
   Government ZC Bonds - Obligations 0.031579        28674.669505            3.16

Utility:
[1.0302201  1.0425515  1.01714904 ... 1.035176   1.03123383 1.04076793]

Probabilit

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2052
[DEBUG] Gross Gains (Normal account): 24655.96
[DEBUG] Tax Calculated (Normal account): 6657.11
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.000025        2.612579e+01            0.00
        Developed Markets - Equities 0.972932        1.029155e+06           97.29
Emerging Markets State - Obligations 0.001251        1.323406e+03            0.13
      High Yield Bonds - Obligations 0.001858        1.965894e+03            0.19
Investment Grade Bonds - Obligations 0.002243        2.372375e+03            0.22
   Government ZC Bonds - Obligations 0.021691        2.294408e+04            2.17

Utility:
[1.02212392 1.02474995 1.02037086 ... 1.01008748 1.         1.00848169]

Probabilit

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2053
[DEBUG] Gross Gains (Normal account): 26668.76
[DEBUG] Tax Calculated (Normal account): 7200.56
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.911713        1.106585e+06           91.17
        Developed Markets - Equities 0.002644        3.209069e+03            0.26
Emerging Markets State - Obligations 0.000222        2.696080e+02            0.02
      High Yield Bonds - Obligations 0.005779        7.014686e+03            0.58
Investment Grade Bonds - Obligations 0.004419        5.363461e+03            0.44
   Government ZC Bonds - Obligations 0.075223        9.130148e+04            7.52

Utility:
[1.00000001 1.03151605 1.         ... 1.04003299 1.04502426 1.05069732]

Probabilit

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2054
[DEBUG] Gross Gains (Normal account): 31196.75
[DEBUG] Tax Calculated (Normal account): 8423.12
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.931058        1.279725e+06           93.11
        Developed Markets - Equities 0.005161        7.093237e+03            0.52
Emerging Markets State - Obligations 0.002622        3.603539e+03            0.26
      High Yield Bonds - Obligations 0.004913        6.753276e+03            0.49
Investment Grade Bonds - Obligations 0.000621        8.540954e+02            0.06
   Government ZC Bonds - Obligations 0.055625        7.645554e+04            5.56

Utility:
[1.03981637 1.00000003 1.03981637 ... 1.         1.01910427 1.00000003]

Probabilit

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2055
[DEBUG] Gross Gains (Normal account): 35200.23
[DEBUG] Tax Calculated (Normal account): 9504.06
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.942410        1.453312e+06           94.24
        Developed Markets - Equities 0.000897        1.384012e+03            0.09
Emerging Markets State - Obligations 0.002043        3.149880e+03            0.20
      High Yield Bonds - Obligations 0.000542        8.365290e+02            0.05
Investment Grade Bonds - Obligations 0.002145        3.307914e+03            0.21
   Government ZC Bonds - Obligations 0.051962        8.013228e+04            5.20

Utility:
[1.03120158 1.02884685 1.03236738 ... 1.03120158 1.0335251  1.02765862]

Probabilit

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2056
[DEBUG] Gross Gains (Normal account): 39813.68
[DEBUG] Tax Calculated (Normal account): 10749.69
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.961582        1.650638e+06           96.16
        Developed Markets - Equities 0.002298        3.944029e+03            0.23
Emerging Markets State - Obligations 0.001951        3.348949e+03            0.20
      High Yield Bonds - Obligations 0.000839        1.439537e+03            0.08
Investment Grade Bonds - Obligations 0.002072        3.557018e+03            0.21
   Government ZC Bonds - Obligations 0.031259        5.365883e+04            3.13

Utility:
[1.03815057 1.01537493 0.99837209 ... 1.         0.99998882 1.02023072]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2057
[DEBUG] Gross Gains (Normal account): 41917.68
[DEBUG] Tax Calculated (Normal account): 11317.77
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.932988        1.771438e+06           93.30
        Developed Markets - Equities 0.004079        7.744580e+03            0.41
Emerging Markets State - Obligations 0.001384        2.628045e+03            0.14
      High Yield Bonds - Obligations 0.001846        3.505179e+03            0.18
Investment Grade Bonds - Obligations 0.004067        7.722653e+03            0.41
   Government ZC Bonds - Obligations 0.055636        1.056343e+05            5.56

Utility:
[1.01264733 1.02832605 1.03908567 ... 1.00000017 1.03673466 0.99999789]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2058
[DEBUG] Gross Gains (Normal account): 44325.90
[DEBUG] Tax Calculated (Normal account): 11967.99
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.921916        1.923984e+06           92.19
        Developed Markets - Equities 0.002531        5.282636e+03            0.25
Emerging Markets State - Obligations 0.000542        1.131245e+03            0.05
      High Yield Bonds - Obligations 0.002841        5.929499e+03            0.28
Investment Grade Bonds - Obligations 0.002263        4.722997e+03            0.23
   Government ZC Bonds - Obligations 0.069906        1.458892e+05            6.99

Utility:
[0.99999944 1.02026739 0.99999745 ... 1.04088869 1.02391346 1.01906497]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2059
[DEBUG] Gross Gains (Normal account): 50436.91
[DEBUG] Tax Calculated (Normal account): 13617.96
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.972455        2.219193e+06           97.25
        Developed Markets - Equities 0.002630        6.002333e+03            0.26
Emerging Markets State - Obligations 0.000954        2.176406e+03            0.10
      High Yield Bonds - Obligations 0.000068        1.541551e+02            0.01
Investment Grade Bonds - Obligations 0.002399        5.473996e+03            0.24
   Government ZC Bonds - Obligations 0.021494        4.905134e+04            2.15

Utility:
[1.02044403 1.00628068 1.02773492 ... 1.         1.04958551 1.01689172]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2060
[DEBUG] Gross Gains (Normal account): 53220.62
[DEBUG] Tax Calculated (Normal account): 14369.57
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.973611        2.421570e+06           97.36
        Developed Markets - Equities 0.000569        1.414650e+03            0.06
Emerging Markets State - Obligations 0.001420        3.531245e+03            0.14
      High Yield Bonds - Obligations 0.002290        5.695947e+03            0.23
Investment Grade Bonds - Obligations 0.001705        4.240204e+03            0.17
   Government ZC Bonds - Obligations 0.020406        5.075294e+04            2.04

Utility:
[1.00835013 1.02153603 1.02513964 ... 1.02359124 1.0060363  1.05586659]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2061
[DEBUG] Gross Gains (Normal account): 55516.32
[DEBUG] Tax Calculated (Normal account): 14989.41
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.961995        2.610411e+06           96.20
        Developed Markets - Equities 0.003128        8.486969e+03            0.31
Emerging Markets State - Obligations 0.005612        1.522959e+04            0.56
      High Yield Bonds - Obligations 0.005178        1.405141e+04            0.52
Investment Grade Bonds - Obligations 0.002080        5.644962e+03            0.21
   Government ZC Bonds - Obligations 0.022006        5.971454e+04            2.20

Utility:
[0.99995776 0.99999976 1.03243086 ... 1.03752115 1.01437898 1.04894055]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2062
[DEBUG] Gross Gains (Normal account): 56030.20
[DEBUG] Tax Calculated (Normal account): 15128.15
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.941193        2.775051e+06           94.12
        Developed Markets - Equities 0.000793        2.337431e+03            0.08
Emerging Markets State - Obligations 0.003880        1.143923e+04            0.39
      High Yield Bonds - Obligations 0.004305        1.269194e+04            0.43
Investment Grade Bonds - Obligations 0.006404        1.888200e+04            0.64
   Government ZC Bonds - Obligations 0.043426        1.280383e+05            4.34

Utility:
[0.99981875 0.99845942 1.01574847 ... 0.98932854 0.99997131 0.99959599]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2063
[DEBUG] Gross Gains (Normal account): 58427.87
[DEBUG] Tax Calculated (Normal account): 15775.52
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.494949e-01        3.030134e+06           94.95
        Developed Markets - Equities 0.000000e+00        0.000000e+00            0.00
Emerging Markets State - Obligations 7.082578e-17        2.260271e-10            0.00
      High Yield Bonds - Obligations 1.950180e-15        6.223630e-09            0.00
Investment Grade Bonds - Obligations 1.762409e-16        5.624396e-10            0.00
   Government ZC Bonds - Obligations 5.050505e-02        1.611773e+05            5.05

Utility:
[0.96666781 0.99997581 0.99997611 ... 0.99942498 1.046

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2064
[DEBUG] Gross Gains (Normal account): 58357.69
[DEBUG] Tax Calculated (Normal account): 15756.58
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.934526        3.218806e+06           93.45
        Developed Markets - Equities 0.002830        9.747958e+03            0.28
Emerging Markets State - Obligations 0.004216        1.452265e+04            0.42
      High Yield Bonds - Obligations 0.002562        8.824514e+03            0.26
Investment Grade Bonds - Obligations 0.004436        1.527811e+04            0.44
   Government ZC Bonds - Obligations 0.051430        1.771407e+05            5.14

Utility:
[0.99933816 0.99733628 1.021805   ... 0.99972176 1.03757362 1.        ]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2065
[DEBUG] Gross Gains (Normal account): 58543.64
[DEBUG] Tax Calculated (Normal account): 15806.78
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.931801        3.453770e+06           93.18
        Developed Markets - Equities 0.005096        1.888853e+04            0.51
Emerging Markets State - Obligations 0.001111        4.116446e+03            0.11
      High Yield Bonds - Obligations 0.000088        3.275543e+02            0.01
Investment Grade Bonds - Obligations 0.002215        8.209778e+03            0.22
   Government ZC Bonds - Obligations 0.059689        2.212408e+05            5.97

Utility:
[0.99157901 1.01124224 0.9996076  ... 0.89261717 0.99500353 1.03015742]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2066
[DEBUG] Gross Gains (Normal account): 61131.66
[DEBUG] Tax Calculated (Normal account): 16505.55
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.003410        1.356750e+04            0.34
        Developed Markets - Equities 0.962076        3.828292e+06           96.21
Emerging Markets State - Obligations 0.009119        3.628785e+04            0.91
      High Yield Bonds - Obligations 0.000299        1.188710e+03            0.03
Investment Grade Bonds - Obligations 0.010441        4.154588e+04            1.04
   Government ZC Bonds - Obligations 0.014655        5.831605e+04            1.47

Utility:
[0.87457199 0.9816177  0.99883524 ... 0.79546837 0.99999614 0.99999862]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2067
[DEBUG] Gross Gains (Normal account): 59346.00
[DEBUG] Tax Calculated (Normal account): 16023.42
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.961578        4.101258e+06           96.16
        Developed Markets - Equities 0.000766        3.268845e+03            0.08
Emerging Markets State - Obligations 0.001391        5.934710e+03            0.14
      High Yield Bonds - Obligations 0.002362        1.007525e+04            0.24
Investment Grade Bonds - Obligations 0.002823        1.204190e+04            0.28
   Government ZC Bonds - Obligations 0.031078        1.325534e+05            3.11

Utility:
[0.98765556 0.99038424 0.93898083 ... 0.95373275 0.88280514 0.99999735]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2068
[DEBUG] Gross Gains (Normal account): 53293.18
[DEBUG] Tax Calculated (Normal account): 14389.16
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.934651        4.264280e+06           93.47
        Developed Markets - Equities 0.001686        7.690866e+03            0.17
Emerging Markets State - Obligations 0.003324        1.516466e+04            0.33
      High Yield Bonds - Obligations 0.000546        2.490687e+03            0.05
Investment Grade Bonds - Obligations 0.017469        7.970215e+04            1.75
   Government ZC Bonds - Obligations 0.042324        1.930997e+05            4.23

Utility:
[0.98300834 0.99979198 0.91473964 ... 0.77926905 0.93295899 0.91473964]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2069
[DEBUG] Gross Gains (Normal account): 52725.33
[DEBUG] Tax Calculated (Normal account): 14235.84
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.636329e-01        4.692310e+06           96.36
        Developed Markets - Equities 3.374936e-08        1.643390e-01            0.00
Emerging Markets State - Obligations 2.581657e-03        1.257111e+04            0.26
      High Yield Bonds - Obligations 2.116461e-03        1.030589e+04            0.21
Investment Grade Bonds - Obligations 9.889963e-03        4.815815e+04            0.99
   Government ZC Bonds - Obligations 2.177897e-02        1.060504e+05            2.18

Utility:
[0.92895014 0.99987563 0.88852387 ... 0.99837293 0.997

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2070
[DEBUG] Gross Gains (Normal account): 50999.79
[DEBUG] Tax Calculated (Normal account): 13769.94
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset       Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 9.900000e-01        5.139724e+06            99.0
        Developed Markets - Equities 1.620179e-14        8.411386e-08             0.0
Emerging Markets State - Obligations 1.668890e-16        8.664275e-10             0.0
      High Yield Bonds - Obligations 1.059131e-16        5.498626e-10             0.0
Investment Grade Bonds - Obligations 0.000000e+00        0.000000e+00             0.0
   Government ZC Bonds - Obligations 1.000000e-02        5.191641e+04             1.0

Utility:
[0.82460961 0.98303341 0.99995021 ... 0.9996772  0.999

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2071
[DEBUG] Gross Gains (Normal account): 31188.02
[DEBUG] Tax Calculated (Normal account): 8420.77
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.951247        5.108763e+06           95.12
        Developed Markets - Equities 0.000764        4.103123e+03            0.08
Emerging Markets State - Obligations 0.002872        1.542504e+04            0.29
      High Yield Bonds - Obligations 0.000256        1.375440e+03            0.03
Investment Grade Bonds - Obligations 0.007412        3.980644e+04            0.74
   Government ZC Bonds - Obligations 0.037448        2.011206e+05            3.74

Utility:
[0.99999885 0.92336073 1.         ... 0.99667382 0.99988843 0.86877775]

Probabilit

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2072
[DEBUG] Gross Gains (Normal account): 19369.47
[DEBUG] Tax Calculated (Normal account): 5229.76
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.981781        5.451839e+06           98.18
        Developed Markets - Equities 0.001109        6.156898e+03            0.11
Emerging Markets State - Obligations 0.001256        6.972308e+03            0.13
      High Yield Bonds - Obligations 0.000729        4.050745e+03            0.07
Investment Grade Bonds - Obligations 0.003743        2.078497e+04            0.37
   Government ZC Bonds - Obligations 0.011383        6.320781e+04            1.14

Utility:
[0.98951862 0.98137939 0.86542532 ... 0.82937712 0.78135516 0.89966101]

Probabilit

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2073
[DEBUG] Gross Gains (Normal account): 56004.82
[DEBUG] Tax Calculated (Normal account): 15121.30
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.206535        1.186956e+06           20.65
        Developed Markets - Equities 0.111993        6.436212e+05           11.20
Emerging Markets State - Obligations 0.147108        8.454288e+05           14.71
      High Yield Bonds - Obligations 0.140597        8.080083e+05           14.06
Investment Grade Bonds - Obligations 0.049462        2.842559e+05            4.95
   Government ZC Bonds - Obligations 0.344306        1.978728e+06           34.43

Utility:
[0.97564764 0.87420058 0.77874533 ... 0.90789458 0.83844516 0.93788105]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar power
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2074
[DEBUG] Gross Gains (Normal account): 83485.59
[DEBUG] Tax Calculated (Normal account): 24938.95
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B           100.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.002385        1.396281e+04            0.24
        Developed Markets - Equities 0.000188        1.099445e+03            0.02
Emerging Markets State - Obligations 0.000112        6.532581e+02            0.01
      High Yield Bonds - Obligations 0.002526        1.478563e+04            0.25
Investment Grade Bonds - Obligations 0.001783        1.043409e+04            0.18
   Government ZC Bonds - Obligations 0.993006        5.812280e+06           99.30

Utility:
[0.89904362 0.96393693 0.99973168 ... 0.81764835 0.79418537 1.        ]

Probabili

C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1
C:\Users\admin\AppData\Local\Temp\ipykernel_4268\4021808357.py:3: RuntimeWarning: invalid value encountered in scalar divide
  required_return = (goal_vector[1] / (pool * goal_allocation))**(1 / goal_vector[2]) - 1


[DEBUG] Final weight sum: 1.0000000000
[DEBUG] Year: 2075
[DEBUG] Gross Gains (Normal account): 0.00
[DEBUG] Tax Calculated (Normal account): 0.00
Optimal Across-Goal Allocation:
Goal  Allocation (%)
   A             0.0
   B             0.0
   C             0.0
   D             0.0

Optimal Aggregate Investment Allocation:
                               Asset   Weight  Invested Amt (DKK)  Allocation (%)
         Emerging Markets - Equities 0.058865                 0.0            5.89
        Developed Markets - Equities 0.075075                 0.0            7.51
Emerging Markets State - Obligations 0.014751                 0.0            1.48
      High Yield Bonds - Obligations 0.086063                 0.0            8.61
Investment Grade Bonds - Obligations 0.098347                 0.0            9.83
   Government ZC Bonds - Obligations 0.666899                 0.0           66.69

Utility:
[1. 1. 1. ... 1. 1. 1.]

Probability of Achieving Each Goal at Optimal Allocation:
Goal A:

In [126]:

# V7C: Export new asset-level log for debugging
pd.DataFrame(asset_level_log).to_csv(os.path.join(output_folder, "asset_returns_log.csv"), index=False)
